### ISSUE TITLE
Managing Consumer Groups: stop consuming before seeking

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data-university/02-hands-on-redpanda-getting-started#1]
The `rpk group seek groupA --to start` command doesn’t work unless we specifically do `ctrl-c` the previous `rpk topic consume song_likes --group groupA` command. By design, the group member has to be empty to tweak the offset.

The seek commands fails as follows, otherwise.
```
daisuke:~/ $ rpk group seek groupA --to start
TOPIC       PARTITION  PRIOR-OFFSET  CURRENT-OFFSET  ERROR
song_likes  0          -1            -1              UNKNOWN_MEMBER_ID: The coordinator is not aware of this member.
song_likes  1          -1            -1              UNKNOWN_MEMBER_ID: The coordinator is not aware of this member.
song_likes  2          -1            -1              UNKNOWN_MEMBER_ID: The coordinator is not aware of this member.
song_likes  3          -1            -1              UNKNOWN_MEMBER_ID: The coordinator is not aware of this member.
song_likes  4          -1            -1              UNKNOWN_MEMBER_ID: The coordinator is not aware of this member.
song_likes  5          -1            -1              UNKNOWN_MEMBER_ID: The coordinator is not aware of this member.
```

<img width="1242" alt="image (24)" src="https://user-images.githubusercontent.com/350206/179958857-347dc421-59ad-4a75-af6c-7a4431b64435.png">

**Comment by mitch-seymour** [comment]
Thanks for opening this issue. I added a reminder for students to exit the previously running consumer session:

> Note: if you are still running a consumer in another tab, be sure to exit that session first with Ctrl-C before executing the following commands.
