### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data-university/02-hands-on-redpanda-getting-started#2]
<img width="1098" alt="image (25)" src="https://user-images.githubusercontent.com/350206/179959034-fa01a16f-fec2-4021-866a-3f7537c0830c.png">

The link highlighted points to [https://github.com/redpanda-data-university/02-hands-on-redpanda-getting-started/b[…]a-tutorial-maven/src/main/java/com/example/ProducerExample.java](https://github.com/redpanda-data-university/02-hands-on-redpanda-getting-started/blob/main/05-basic-streaming/java-tutorial-maven/src/main/java/com/example/ProducerExample.java) but it doesn’t exist. It should be [https://github.com/redpanda-data-university/02-hands-on-redpanda-getting-started/b[…]a-tutorial-maven/src/main/java/com/example/ProducerExample.java](https://github.com/redpanda-data-university/02-hands-on-redpanda-getting-started/blob/main/03-basic-streaming/java-tutorial-maven/src/main/java/com/example/ProducerExample.java)

The link to ConsumerExample.java is also wrong.

**Comment by mitch-seymour** [comment]
Thanks for opening this issue. I fixed the links :)
