### ISSUE TITLE
Prepare a topic before executing the sample

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data-university/02-hands-on-redpanda-getting-started#3]
<img width="1072" alt="image (26)" src="https://user-images.githubusercontent.com/350206/179959372-97429687-288b-4381-9042-d2227647ff73.png">

Before we execute the example producer, we should ensure the topic `greetings` is created. I couldn’t see the instruction to create the topic in the course, IIUC.

**Comment by mitch-seymour** [comment]
Thanks. We actually do have this instruction in Lesson I, which contains the Prerequisites for all of the tutorials:
https://university.redpanda.com/courses/take/hands-on-redpanda-getting-started/texts/34493501-prerequisites.

We reference this from the intro video and also the Java lesson. Taken from the Java lesson:

> In addition to the prerequisites that we mentioned in Lesson I, this lesson requires you to have...

**Comment by daisukebe** [comment]
Oops, thanks!
